<?xml version="1.0" encoding="utf-8"?>
<Database Name="UserOrderItems" EntityNamespace="Db.DataAccess.DataSet" ContextNamespace="Db.DataAccess.DataSet" Class="DbDataContext" Serialization="Unidirectional" EntityBase="DbEntity" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Item" Member="Items">
    <Type Name="Item">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FK_Item_Order" Member="Order" ThisKey="OrderId" OtherKey="Id" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Order" Member="Orders">
    <Type Name="Order">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InsertTimestamp" Type="System.DateTime" DbType="DateTime2(7) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FK_Item_Order" Member="Items" ThisKey="Id" OtherKey="OrderId" Type="Item" DeleteRule="NO ACTION" />
      <Association Name="FK_Order_User" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.User" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="FK_Order_User" Member="Orders" ThisKey="Id" OtherKey="UserId" Type="Order" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Function Name="dbo.sp_alterdiagram" Method="Sp_alterdiagram">
    <Parameter Name="diagramname" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="owner_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="version" Type="System.Int32" DbType="Int" />
    <Parameter Name="definition" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" />
    <Return Type="System.Int32" DbType="Int" />
  </Function>
  <Function Name="dbo.sp_creatediagram" Method="Sp_creatediagram">
    <Parameter Name="diagramname" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="owner_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="version" Type="System.Int32" DbType="Int" />
    <Parameter Name="definition" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" />
    <Return Type="System.Int32" DbType="Int" />
  </Function>
  <Function Name="dbo.sp_dropdiagram" Method="Sp_dropdiagram">
    <Parameter Name="diagramname" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="owner_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" DbType="Int" />
  </Function>
  <Function Name="dbo.sp_helpdiagramdefinition" Method="Sp_helpdiagramdefinition">
    <Parameter Name="diagramname" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="owner_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="Sp_helpdiagramdefinitionResult">
      <Column Name="version" Member="Version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="definition" Member="Definition" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_helpdiagrams" Method="Sp_helpdiagrams">
    <Parameter Name="diagramname" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="owner_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="Sp_helpdiagramsResult">
      <Column Name="Database" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Owner" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_renamediagram" Method="Sp_renamediagram">
    <Parameter Name="diagramname" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="owner_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="new_diagramname" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Int32" DbType="Int" />
  </Function>
</Database>